Game logic
tta2yta/Tic_tac_toe pull request #3
Opened 2021-02-28 08:48 UTC by tta2yta

In the third milestone section of the Tic Tac Toe game, we have created a branch called the game_logic. In this branch, we have created two classes called player and game. These classes hold instance variables and methods that represent respective objects.  In the main file, we created objects of these classes to access the needed logic implementation of the member functions in each class. This project is the implementation of the Tic Tac Toe game in the ruby language.

Kindly review my code before I merge it.
Thanks in advance.

2021-02-28 17:10 UTC, bini-i requested changes
# Status: Changes Required :yellow_circle: 
### Hello  team :wave: 

### I really like your project, 
- simple and understandable, 
-  your methods are small and do one thing only, and 
-  thank you for including a decent README early in the milestone.

#### Please work on the requirements listed below and submit a request for a new review:
- use attr_readers/attr_writers to easily access and modify attributes of your objects
eg:- name attributes of a player can be set at initialization and be accessed if you set attr_readers for it and also one player will have one name instead of an array of names.
- you can DRY repetitive code to obtain players information in main.rb by factoring them into a method.

#### If you have any question kindly reach me on slack @Binyam Hailemeskel

### HAPPY CODING :computer: :blush: 

> #### Reviewed by Binyam Hailemeskel (TSE)
> GitHub: [@bini-i](https://github.com/bini-i)
> Twitter: [@binyamshewa](https://twitter.com/binyamshewa)
> LinkedIn: [LinkedIn](https://www.linkedin.com/in/binyam-hailemeskel-728048151/)

2021-03-01 08:07 UTC, tta2yta commented
Hello. Thank you for your feedback. I have added one attr_reader  instance variable to the class player as you said to use attr_readers/attr_writers. Moreover, to achieve the DRY principle in the main file, we have created one function called enter_names that handles the names of players.

Kindly review my code before I merge it.
Thanks in advance.

2021-03-01 08:16 UTC, lekegitrepo requested changes
## Status: Changes Required! :recycle:
### Good job :+1:  Team
#### The required changes are well implemented. However, there is commented code in the `main` file

#### commented code:
 - Remove the commented codes.

#### _Reviewed by Temitayo Adeleke_

2021-03-01 08:16 UTC, lekegitrepo commented on bin/main
> +  # puts "Player One Your Name is #{pl.get_player_name(0)}"
- Remove commented code.

2021-03-01 08:16 UTC, lekegitrepo commented on bin/main
> +  # puts "Player two Your Name is #{pl.get_player_name(1)}"
- Remove commented code

2021-03-01 08:44 UTC, tta2yta commented
Hello. Thank you for your code reviews. We have removed the commented codes from the main.

Kindly review my code before I merge it.
Thanks in advance.

2021-03-01 08:48 UTC, lekegitrepo approved these changes
## Status: Approved :heavy_check_mark:
### Good job :+1: for implementing the required changes.
#### This project is approved :white_check_mark:

#### _Reviewed by Temitayo Adeleke_

2021-03-01 08:54 UTC, merged